In [1]:
import numpy as np

In [2]:
np.random.rand(10)

array([0.04039441, 0.41052176, 0.73787656, 0.99386597, 0.74362684,
       0.06763564, 0.08726388, 0.08876438, 0.06051778, 0.57354282])

In [3]:
np.random.randn(10)

array([-0.75764437, -0.87460802, -0.86129052, -0.85296373,  1.33348135,
       -1.40840589,  0.56730477, -0.34794338,  0.00658789, -0.72673908])

In [51]:
np.random.randint(10,20,10)

array([15, 15, 11, 12, 11, 14, 13, 16, 18, 15], dtype=int32)